"""empty message

Revision ID: 0dedff865af5
Revises: c29f0e53fadd
Create Date: 2019-03-15 12:09:28.739441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dedff865af5'
down_revision = 'c29f0e53fadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'contacts', sa.Column('name', sa.String(length=30), nullable=False)
    )
    op.add_column(
        'contacts', sa.Column('starred', sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'starred')
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
